<?php

namespace Pathologic\Commerce\Booking;

class Model extends \autoTable
{
    protected $table = 'reservations';
    public $default_field = [
        'docid'     => 0,
        'begin'     => '',
        'end'       => '',
        'orderid'   => 0,
        'description' => '',
        'hash' => '',
        'createdon' => '',
        'updatedon' => '',
    ];

    public function set($key, $value)
    {
        if($key == 'begin' || $key == 'end') {
            $value = date('Y-m-d', strtotime($value));
        }

        return parent::set($key, $value); // TODO: Change the autogenerated stub
    }

    public function save($fire_events = false, $clearCache = false)
    {
        if(!$this->newDoc) {
            $this->set('updatedon', date('Y-m-d H:i:s', $this->getTime(time())));
        } else {
            $this->set('createdon', date('Y-m-d H:i:s', $this->getTime(time())));
            if(empty($this->get('hash'))) {
                $this->set('hash', \APIhelpers::genPass(32, 'a0'));
            }
        }

        return parent::save($fire_events, $clearCache); // TODO: Change the autogenerated stub
    }


    public function createTable()
    {
        $this->query("CREATE TABLE IF NOT EXISTS {$this->makeTable($this->table)} (
            `id` INT(11) AUTO_INCREMENT,
            `docid` INT(11) NOT NULL,
            `orderid` INT(11),
            `begin` DATE,
            `end` DATE,
            `description` TEXT,
            `hash` varchar(32) NOT NULL,
            `createdon` DATETIME DEFAULT CURRENT_TIMESTAMP ,
            `updatedon` DATETIME,
            PRIMARY KEY (`id`),
            KEY `reservation` (`docid`, `begin`, `end`),
            KEY `period` (`begin`, `end`),
            KEY `hash` (`id`, `hash`),
            KEY `orderid` (`orderid`)
            ) ENGINE=InnoDB
        ");
        $this->query("
            INSERT IGNORE INTO {$this->makeTable('system_eventnames')} (`name`, `groupname`) VALUES
            ('OnBookingCalculatePrice', 'Booking Events'),
            ('OnBookingItemCheck', 'Booking Events')
        ");
    }
}
